stages:
  - test
  - build

variables:
  LANG: "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"

# Make sure Homebrew Ruby is used (not macOS system Ruby 2.6)
.setup_ruby: &setup_ruby
  - ruby --version
  - gem install bundler --no-document
  - bundle install

test:
  stage: test
  tags:
    - macOS
  script:
    - export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
    - *setup_ruby
    - bundle exec fastlane test

build:
  stage: build
  tags:
    - macOS
  script:
    - export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
    - *setup_ruby
    - bundle exec fastlane build
  needs: [test]
